<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="classes" name="Failed suite [planit]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="classes" name=" Validate_errors_are_gone (failed)">
    <classes>
      <class name="automation.testcases.Verify_itemsincart">
        <methods>
          <include name="closeBrowser"/>
          <include name="verifyItemsinCart"/>
          <include name="setDown"/>
          <include name="configBrowser"/>
          <include name="setExtent"/>
        </methods>
      </class> <!-- automation.testcases.Verify_itemsincart -->
      <class name="automation.testcases.Validate_Successful_Message">
        <methods>
          <include name="validateSuccess"/>
          <include name="closeBrowser"/>
          <include name="setDown"/>
          <include name="configBrowser"/>
          <include name="setExtent"/>
        </methods>
      </class> <!-- automation.testcases.Validate_Successful_Message -->
      <class name="automation.testcases.Validate_errors_invalid_data">
        <methods>
          <include name="closeBrowser"/>
          <include name="invalidDataErrors"/>
          <include name="setDown"/>
          <include name="configBrowser"/>
          <include name="setExtent"/>
        </methods>
      </class> <!-- automation.testcases.Validate_errors_invalid_data -->
    </classes>
  </test> <!--  Validate_errors_are_gone (failed) -->
</suite> <!-- Failed suite [planit] -->
